// <auto-generated />
using DeveloperDashboard.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperDashboard.Migrations
{
    [DbContext(typeof(DeveloperDashboardContext))]
    [Migration("20231113181053_googleSearch")]
    partial class googleSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DashboardWidget", b =>
                {
                    b.Property<int>("DashboardsId")
                        .HasColumnType("integer")
                        .HasColumnName("dashboards_id");

                    b.Property<int>("WidgetsId")
                        .HasColumnType("integer")
                        .HasColumnName("widgets_id");

                    b.HasKey("DashboardsId", "WidgetsId")
                        .HasName("pk_dashboard_widget");

                    b.HasIndex("WidgetsId")
                        .HasDatabaseName("ix_dashboard_widget_widgets_id");

                    b.ToTable("dashboard_widget", (string)null);
                });

            modelBuilder.Entity("DeveloperDashboard.Models.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_dashboards");

                    b.ToTable("dashboards", (string)null);
                });

            modelBuilder.Entity("DeveloperDashboard.Models.Widget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_widgets");

                    b.ToTable("widgets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "_UrlShortener",
                            Height = 2,
                            Name = "Url Shortener",
                            Width = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "_GoogleSearch",
                            Height = 2,
                            Name = "Google Search",
                            Width = 2
                        });
                });

            modelBuilder.Entity("DashboardWidget", b =>
                {
                    b.HasOne("DeveloperDashboard.Models.Dashboard", null)
                        .WithMany()
                        .HasForeignKey("DashboardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dashboard_widget_dashboards_dashboards_id");

                    b.HasOne("DeveloperDashboard.Models.Widget", null)
                        .WithMany()
                        .HasForeignKey("WidgetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dashboard_widget_widgets_widgets_id");
                });
#pragma warning restore 612, 618
        }
    }
}
